theme: minima
title: About me
author: Milan George
email: mmg210001@utdallas.edu
description: > # this means to ignore newlines until "baseurl:"
 talks about who I am and my skillset.
# social links
github_username:  milangeorge98 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
